export type VisaProgram = {
  name: string;
  category:
    | "Entrepreneur Visa"
    | "Startup Visa"
    | "Investor Visa"
    | "Golden Visa"
    | "Residency by Investment"
    | "Work Permit"
    | "Digital Nomad"
    | "Citizenship";
  minInvestment: string;
  duration: string;
  processingTime: string;
  familyIncluded: boolean;
  pathToPR: boolean;
  requirements: string[];
  steps: string[];
  officialUrl: string;
  summary: string;
};

// Helper to keep entries compact
const p = (
  name: string,
  category: VisaProgram["category"],
  minInvestment: string,
  duration: string,
  processingTime: string,
  familyIncluded: boolean,
  pathToPR: boolean,
  requirements: string[],
  steps: string[],
  officialUrl: string,
  summary: string,
): VisaProgram => ({
  name, category, minInvestment, duration, processingTime, familyIncluded, pathToPR, requirements, steps, officialUrl, summary,
});

export const VISA_PROGRAMS: Record<string, VisaProgram[]> = {
  US: [
    p("E-2 Investor Visa", "Investor Visa", "$100,000+", "5 yrs (renewable)", "2-6 months", true, false,
      ["Treaty-country nationality", "Substantial at-risk investment", "Active US business", "Create US jobs"],
      ["Form a US entity", "Wire funds and lease premises", "File DS-160 + DS-156E", "Attend consular interview"],
      "https://travel.state.gov/content/travel/en/us-visas/employment/treaty-trader-investor-visa-e.html",
      "Treaty investor visa for substantial business investment in a US enterprise."),
    p("EB-5 Immigrant Investor", "Residency by Investment", "$800,000 (TEA) / $1.05M", "Permanent", "24-48 months", true, true,
      ["Lawful source of funds", "10 full-time US jobs", "Investment in new commercial enterprise"],
      ["Choose direct or Regional Center", "File I-526E", "Consular processing / adjust status", "File I-829 to remove conditions"],
      "https://www.uscis.gov/eb-5",
      "Green card via investment in a US business creating 10+ jobs."),
    p("L-1 Intracompany Transfer", "Work Permit", "—", "1-7 yrs", "2-4 months", true, true,
      ["Qualifying foreign employer", "1 yr abroad in last 3", "Executive/managerial or specialized role"],
      ["File I-129 (L-1A/B)", "Consular visa stamping", "Enter US and begin role"],
      "https://www.uscis.gov/working-in-the-united-states/temporary-workers/l-1a-intracompany-transferee-executive-or-manager",
      "Transfer executives or specialized employees to a US branch."),
    p("O-1 Extraordinary Ability", "Work Permit", "—", "3 yrs (renewable)", "2-3 months", true, true,
      ["Sustained acclaim", "Meet 3+ of 8 USCIS criteria", "US petitioner or agent"],
      ["Assemble evidence portfolio", "File I-129", "Consular visa or change of status"],
      "https://www.uscis.gov/working-in-the-united-states/temporary-workers/o-1-visa-individuals-with-extraordinary-ability-or-achievement",
      "For founders & talent with extraordinary achievement in their field."),
  ],
  GB: [
    p("Innovator Founder Visa", "Startup Visa", "No fixed amount", "3 yrs", "3-8 weeks", true, true,
      ["Endorsed innovative business plan", "English B2", "£1,270 maintenance funds"],
      ["Secure endorsement from approved body", "Apply online + biometrics", "Enter UK and set up business"],
      "https://www.gov.uk/innovator-founder-visa",
      "For experienced entrepreneurs launching innovative, scalable UK businesses."),
    p("Global Talent Visa", "Work Permit", "—", "Up to 5 yrs", "3-8 weeks", true, true,
      ["Endorsement (Tech Nation/Royal Society/UKRI/Arts Council)"],
      ["Apply for endorsement", "Apply for the visa", "Enter UK"],
      "https://www.gov.uk/global-talent",
      "Endorsed leaders in tech, science, arts, research."),
    p("Skilled Worker Visa", "Work Permit", "—", "Up to 5 yrs", "3-8 weeks", true, true,
      ["Sponsor licence + Certificate of Sponsorship", "Salary threshold (£38,700)", "English B1"],
      ["Receive CoS from sponsor", "Apply online + biometrics"],
      "https://www.gov.uk/skilled-worker-visa",
      "Sponsored employment in a qualifying UK role."),
  ],
  DE: [
    p("Self-Employment Visa (§21 AufenthG)", "Entrepreneur Visa", "€100,000+ recommended", "3 yrs", "2-4 months", true, true,
      ["Viable business plan", "Regional economic interest", "Financing proof"],
      ["Prepare plan + financials", "Apply at German consulate", "Register business in Germany"],
      "https://www.make-it-in-germany.com/en/visa-residence/types/self-employment",
      "For entrepreneurs whose business serves an economic interest in Germany."),
    p("Freelancer Visa (§21.5)", "Entrepreneur Visa", "Proof of income", "3 yrs", "2-4 months", true, true,
      ["Liberal profession", "Client letters of intent", "Health insurance"],
      ["Apply at consulate", "Register address in Germany", "Convert to residence permit"],
      "https://www.make-it-in-germany.com/en/visa-residence/types/self-employment",
      "Liberal-professional visa for freelancers with German clients."),
    p("EU Blue Card", "Work Permit", "—", "4 yrs", "1-3 months", true, true,
      ["University degree", "Job offer ≥ €45,300 (or shortage ≥ €41,041)"],
      ["Signed job contract", "Apply at consulate", "Register in Germany"],
      "https://www.make-it-in-germany.com/en/visa-residence/types/eu-blue-card",
      "Highly-skilled employment with fast-track PR."),
  ],
  CA: [
    p("Start-Up Visa Program", "Startup Visa", "CAD 75K-200K (designated)", "Permanent on approval", "12-24 months", true, true,
      ["Letter of support from designated org", "CLB 5 English/French", "Settlement funds"],
      ["Secure designated investor", "Submit PR application", "Land in Canada"],
      "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/start-visa.html",
      "PR for founders backed by designated VCs, angels, or incubators."),
    p("Self-Employed Persons", "Entrepreneur Visa", "—", "Permanent", "24-36 months", true, true,
      ["Relevant self-employment experience", "Intent + ability to contribute"],
      ["Submit PR application", "Medical/security", "Land in Canada"],
      "https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/self-employed.html",
      "For cultural, athletic, or farming self-employed applicants."),
  ],
  AE: [
    p("UAE Golden Visa", "Golden Visa", "AED 2M (property/funds)", "10 yrs renewable", "2-4 weeks", true, false,
      ["Qualifying investment / talent / specialised skill"],
      ["Apply via ICP / GDRFA portal", "Medical + Emirates ID", "Receive 10-yr residency"],
      "https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/golden-visa",
      "Long-term residency for investors, founders, and talent."),
    p("Green Visa", "Residency by Investment", "AED 1M (investor)", "5 yrs", "2-4 weeks", true, false,
      ["Investor/skilled/freelancer criteria"],
      ["Apply via ICP portal", "Medical + Emirates ID"],
      "https://u.ae/en/information-and-services/visa-and-emirates-id/residence-visas/green-residence",
      "Self-sponsored residency for skilled employees & investors."),
    p("Free Zone Company License", "Entrepreneur Visa", "AED 12K+ setup", "2-3 yrs renewable", "2-6 weeks", true, false,
      ["Free zone license", "Office/flexi-desk"],
      ["Choose free zone", "Incorporate + license", "Investor visa + Emirates ID"],
      "https://u.ae/en/information-and-services/business/doing-business-in-free-zones",
      "Investor visa via a free-zone company (100% foreign ownership)."),
  ],
  SG: [
    p("Global Investor Programme", "Investor Visa", "SGD 10M+", "Permanent", "6-12 months", true, true,
      ["Substantial business/family-office track record"],
      ["Submit application to EDB", "Interview", "Establish SG operations"],
      "https://www.edb.gov.sg/en/how-we-help/incentives-and-schemes/global-investor-programme.html",
      "PR for HNW investors and family-office principals."),
    p("EntrePass", "Entrepreneur Visa", "SGD 50K+ paid-up", "1-2 yrs renewable", "8 weeks", true, true,
      ["Innovative venture", "Funding / IP / accelerator backing"],
      ["Register company", "Apply via MOM", "Renewal criteria (jobs/spend)"],
      "https://www.mom.gov.sg/passes-and-permits/entrepass",
      "Visa for innovative founders building venture-backed startups in Singapore."),
  ],
  AU: [
    p("Business Innovation 188", "Entrepreneur Visa", "AUD 1.25M+", "5 yrs", "12-24 months", true, true,
      ["State/territory nomination", "Business/investment track record"],
      ["Submit EOI in SkillSelect", "Receive nomination", "Lodge 188 application"],
      "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/business-innovation-and-investment-188",
      "Provisional visa for business owners & investors; pathway to 888 PR."),
    p("Global Talent Visa", "Work Permit", "—", "Permanent", "3-6 months", true, true,
      ["Internationally recognised talent in target sector"],
      ["Submit EOI", "Receive invitation", "Lodge visa"],
      "https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/global-talent-visa-858",
      "PR for highly-talented professionals in target sectors."),
  ],
  PT: [
    p("Portugal Golden Visa", "Golden Visa", "€250K-500K (funds/culture)", "5 yrs → citizenship", "6-18 months", true, true,
      ["Qualifying investment", "Clean criminal record", "7 days/yr stay minimum"],
      ["Choose investment route", "Open PT bank account + NIF", "Submit AIMA application"],
      "https://www.aima.gov.pt",
      "Residency for qualifying investment; minimal stay requirements."),
    p("D8 Digital Nomad Visa", "Digital Nomad", "€3,480+/mo income", "2 yrs (renewable)", "2-3 months", true, true,
      ["Remote income from non-PT employer", "Accommodation proof"],
      ["Apply at consulate", "Enter PT + AIMA appointment"],
      "https://vistos.mne.gov.pt",
      "Long-term stay for remote workers with foreign income."),
  ],
  ES: [
    p("Spain Entrepreneur Visa", "Startup Visa", "Innovative business plan", "3 yrs", "1-3 months", true, true,
      ["ENISA favourable report", "Innovative & scalable business"],
      ["Prepare plan for ENISA", "Apply via UGE", "Register in Spain"],
      "https://www.mites.gob.es",
      "ENISA-endorsed innovative entrepreneur residency."),
    p("Digital Nomad Visa", "Digital Nomad", "€2,650+/mo income", "3 yrs (renewable)", "1-2 months", true, true,
      ["Remote work for non-ES employer", "3+ months history"],
      ["Apply at consulate or in ES", "Register + TIE card"],
      "https://www.exteriores.gob.es",
      "Long-stay visa for remote workers; access to Beckham Law tax regime."),
  ],
  CH: [
    p("Swiss Lump-Sum Taxation", "Residency by Investment", "CHF 250K+ annual tax", "Renewable", "3-6 months", true, true,
      ["Non-EU national", "No Swiss employment", "Cantonal negotiation"],
      ["Select canton", "Negotiate lump-sum ruling", "Apply for residence permit"],
      "https://www.ch.ch/en/taxes-and-finances/types-of-taxation/lump-sum-taxation/",
      "Residency for HNW individuals via cantonal lump-sum taxation."),
  ],
  NL: [
    p("Dutch-American Friendship Treaty (DAFT)", "Entrepreneur Visa", "€4,500", "2 yrs renewable", "2-3 months", true, true,
      ["US citizenship", "Registered Dutch business", "€4,500 in business account"],
      ["Register KvK entity", "Open Dutch business bank", "Apply at IND"],
      "https://ind.nl/en/residence-permits/work/self-employed-person",
      "Low-threshold entrepreneur residency for US citizens."),
    p("Highly Skilled Migrant", "Work Permit", "—", "Up to 5 yrs", "2-4 weeks", true, true,
      ["Recognised sponsor employer", "Salary threshold"],
      ["Sponsor files IND application", "Enter NL + register BSN"],
      "https://ind.nl/en/residence-permits/work/highly-skilled-migrant",
      "Fast-track work permit via IND-recognised sponsor employers."),
  ],
  FR: [
    p("French Tech Visa", "Startup Visa", "Funded startup", "4 yrs", "2-3 months", true, true,
      ["Recognised incubator / funded startup / recruited talent"],
      ["Obtain Tech Visa endorsement", "Apply at consulate"],
      "https://visa.lafrenchtech.com",
      "For founders, employees, and investors in French tech."),
    p("Talent Passport - Investor", "Investor Visa", "€300,000+", "4 yrs (renewable)", "2-3 months", true, true,
      ["Direct investment creating/preserving jobs"],
      ["Prepare investment file", "Apply at consulate", "Register in France"],
      "https://france-visas.gouv.fr",
      "Multi-year residency for qualifying French investors."),
  ],
  GR: [
    p("Greece Golden Visa", "Golden Visa", "€250K-800K real estate", "5 yrs (renewable)", "2-4 months", true, true,
      ["Qualifying property investment", "Clean criminal record"],
      ["Choose property + reserve", "Obtain AFM tax ID", "File biometrics"],
      "https://www.mfa.gr",
      "Residency by real-estate investment; no minimum stay."),
  ],
  MT: [
    p("Malta Permanent Residence (MPRP)", "Residency by Investment", "€150K+ (gov contribution + property)", "Permanent", "6-8 months", true, true,
      ["Property purchase/lease", "Government contribution", "Donation to NGO"],
      ["Engage licenced agent", "Due diligence", "Submit application"],
      "https://residencymalta.gov.mt",
      "EU permanent residency for HNW individuals investing in Malta."),
  ],
  IE: [
    p("Start-up Entrepreneur Programme (STEP)", "Startup Visa", "€50,000+", "2 yrs (renewable)", "6-12 weeks", true, true,
      ["Innovative HPSU business", "Funding secured"],
      ["Prepare business plan", "Submit to DoJ evaluation committee"],
      "https://www.irishimmigration.ie",
      "Ireland residency for founders of innovative high-potential startups."),
  ],
  EE: [
    p("Estonia Startup Visa", "Startup Visa", "No fixed amount", "1 yr + extensions", "10-30 days", true, true,
      ["Startup Committee approval", "Innovative & scalable business"],
      ["Apply via Startup Estonia", "Submit visa application"],
      "https://startupestonia.ee/visa",
      "Fast-track visa for founders of innovative, scalable startups."),
  ],
  TR: [
    p("Turkey Citizenship by Investment", "Citizenship", "$400,000 real estate (or $500K bank/funds)", "Permanent", "3-6 months", true, true,
      ["Qualifying investment held 3 yrs", "Clean record"],
      ["Choose investment", "Obtain valuation report", "File citizenship application"],
      "https://www.goc.gov.tr",
      "Direct citizenship by qualifying real-estate or bank investment."),
  ],
  MX: [
    p("Temporary Resident Visa", "Residency by Investment", "~USD 65K assets or ~USD 4K/mo income", "4 yrs → PR", "4-8 weeks", true, true,
      ["Solvency (income or assets)", "No Mexican criminal record"],
      ["Apply at Mexican consulate abroad", "Enter MX + INM canje within 30 days"],
      "https://www.gob.mx/inm",
      "Popular route for remote workers, retirees, and investors with foreign income."),
  ],
  TH: [
    p("Thailand LTR (Long-Term Resident) Visa", "Investor Visa", "$80K/yr income or $500K+ investment", "10 yrs", "2-3 months", true, false,
      ["Wealthy global citizen / pensioner / WFH / high-skilled category"],
      ["Apply via BOI portal", "Endorsement", "Collect visa at embassy or in TH"],
      "https://ltr.boi.go.th",
      "10-year residency for HNW individuals, remote workers, and high-skilled talent."),
  ],
  JP: [
    p("Business Manager Visa", "Entrepreneur Visa", "¥5M capital (~USD 33K)", "1/3/5 yrs", "1-3 months", true, true,
      ["Registered KK/GK company", "Physical office", "Business plan"],
      ["Incorporate JP company", "Lease office", "Apply for COE + visa"],
      "https://www.moj.go.jp/isa/",
      "Residency for founders operating a real, funded business in Japan."),
  ],
};

export const TOP_INVESTMENT_COUNTRIES = ["US", "GB", "DE", "CA", "AE", "SG", "PT", "AE"] as const;
