/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSuggestionsRouteImport } from './routes/app.suggestions'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppPortfolioRouteImport } from './routes/app.portfolio'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppCountriesRouteImport } from './routes/app.countries'
import { Route as AppConverterRouteImport } from './routes/app.converter'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSuggestionsRoute = AppSuggestionsRouteImport.update({
  id: '/suggestions',
  path: '/suggestions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppCountriesRoute = AppCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AppRoute,
} as any)
const AppConverterRoute = AppConverterRouteImport.update({
  id: '/converter',
  path: '/converter',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/converter': typeof AppConverterRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/converter': typeof AppConverterRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/converter': typeof AppConverterRoute
  '/app/countries': typeof AppCountriesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/portfolio': typeof AppPortfolioRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suggestions': typeof AppSuggestionsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/app/assistant'
    | '/app/converter'
    | '/app/countries'
    | '/app/history'
    | '/app/notifications'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/suggestions'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/app/assistant'
    | '/app/converter'
    | '/app/countries'
    | '/app/history'
    | '/app/notifications'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/suggestions'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/signin'
    | '/signup'
    | '/terms'
    | '/app/assistant'
    | '/app/converter'
    | '/app/countries'
    | '/app/history'
    | '/app/notifications'
    | '/app/portfolio'
    | '/app/settings'
    | '/app/suggestions'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suggestions': {
      id: '/app/suggestions'
      path: '/suggestions'
      fullPath: '/app/suggestions'
      preLoaderRoute: typeof AppSuggestionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/portfolio': {
      id: '/app/portfolio'
      path: '/portfolio'
      fullPath: '/app/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/countries': {
      id: '/app/countries'
      path: '/countries'
      fullPath: '/app/countries'
      preLoaderRoute: typeof AppCountriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/converter': {
      id: '/app/converter'
      path: '/converter'
      fullPath: '/app/converter'
      preLoaderRoute: typeof AppConverterRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppConverterRoute: typeof AppConverterRoute
  AppCountriesRoute: typeof AppCountriesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuggestionsRoute: typeof AppSuggestionsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppConverterRoute: AppConverterRoute,
  AppCountriesRoute: AppCountriesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuggestionsRoute: AppSuggestionsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
